// ============================================================================
// INSPIRATIONAL QUOTES - Rotated daily
// ============================================================================

export const QUOTES = [
  "Find joy in the little things.",
  "Joy lives in the moment you notice.",
  "A quiet moment can be everything.",
  "Breathe in the calm. Capture the joy.",
  "Slow down — this moment is enough.",
  "Right now is worth remembering.",
  "You are allowed to pause.",
  "Notice what feels gentle today.",
  "Warm hearts make cozy memories.",
  "Soft lights, soft smiles, soft memories.",
  "Comfort lives in simple moments.",
  "A moment of warmth can change a day.",
  "Create a little cozy wherever you are.",
  "Even ordinary days hold warmth.",
  "Peace can be found in small corners.",
  "Even tiny memories are treasures.",
  "A snapshot is a hug for your memories.",
  "Moments make magic.",
  "Little moments become big memories.",
  "What you notice becomes what you remember.",
  "Some memories whisper instead of shout.",
  "This moment will matter someday.",
  "Celebrate the simple things.",
  "You deserve a peaceful pause.",
  "Let today be light.",
  "There is no rush here.",
  "This is enough for today.",
  "Be kind to the moment you're in.",
  "Let the day unfold gently.",
  "Life is felt in quiet details.",
  "Hold onto the sparkle in small things.",
  "Today tastes like comfort.",
  "A soft moment is still a strong one.",
  "The beauty is already here.",
  "Some joy is barely louder than a breath.",
  "What feels meaningful right now?",
  "What would you like to remember?",
  "Capture what feels true today.",
  "What made you smile, even briefly?",
  "Save this feeling.",
] as const;
